# Dependencies
markdown:         kramdown
highlighter:      rouge
#220928 mathjax 설정 추가하기
lsi: false
excerpt_seperator: "\n\n"
incremental: fasle


# Setup
title:            ฅʕ•ﻌ•ʔ
tagline:          ""
description:      "DurianFarmer's Data Science Farm"
url:              https://durianfarmer.github.io
baseurl:          ''
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'Kyuwook Chai'
  url:            https://durianfarmer.github.io  

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.

tipue_search:
  include:
      pages: false
      collections: []
  exclude:
      files: [search.html, index.html, tags.html]
      categories: []
      tags: []

## (220928) MathJax 사용


## (220928) Collections: 날짜 없는 페이지들(not posts) 업로드 용도
## https://cloudcannon.com/community/learn/jekyll-tutorial/introduction-to-jekyll-collections/
## Use posts when you want to write independent articles, with a publishing date.
## Use collections when you want to group related content, which can have its own page, but date is unimportant.
#####
# collections:
#   pages:
#     output: true
#####
